import { test, expect } from '@playwright/test';
import { clickDialogPadding, clickOutsideDialog } from './helpers.js';

test.skip(process.env.ART_DIRECTOR_EVAL !== '1', 'Optional saved holdout');
for (const width of [1440, 390]) test(`existing system: note and dialog at ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: width === 390 ? 844 : 900 });
  await page.goto('http://127.0.0.1:5194');
  const rows = page.locator('tbody tr');
  await expect(rows).toHaveCount(3);
  await rows.nth(1).click();
  const opener = page.getByRole('button', { name: /^(Add|Edit) note$/ });
  await opener.click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('button', { name: 'Save note' }).click();
  await expect(page.locator('.nd-error')).toContainText('required');
  const note = 'Fictional evaluation: İpek requested a written explanation.\n\nSeveral sentences must remain readable after saving and returning to the selected record.';
  await dialog.getByLabel('Clinical note').fill(note);
  await dialog.getByRole('button', { name: 'Save note' }).click();
  await expect(page.locator('.nd-note-copy')).toHaveText(note);
  await expect(opener).toBeFocused();
  await rows.nth(0).click();
  await expect(page.locator('.nd-note-empty')).toBeVisible();
  await rows.nth(1).click();
  await expect(page.locator('.nd-note-copy')).toHaveText(note);
  await opener.click();
  await dialog.getByLabel('Clinical note').fill('Discard me');
  await dialog.getByRole('button', { name: 'Cancel' }).click();
  await expect(page.locator('.nd-note-copy')).toHaveText(note);
  await opener.click();
  await dialog.getByRole('button', { name: 'Cancel' }).focus();
  await page.keyboard.press('Tab');
  await expect(dialog.getByLabel('Clinical note')).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  await expect(dialog.getByRole('button', { name: 'Cancel' })).toBeFocused();
  await clickDialogPadding(dialog);
  await expect(dialog).toBeVisible();
  const box = await dialog.boundingBox();
  expect(box.x).toBeGreaterThanOrEqual(0);
  expect(box.x + box.width).toBeLessThanOrEqual(width);
  expect(box.y + box.height).toBeLessThanOrEqual(page.viewportSize().height);
  await clickOutsideDialog(dialog);
  await expect(dialog).not.toBeVisible();
  await opener.click();
  await page.keyboard.press('Escape');
  await expect(opener).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
